sudo: required
services:
  - docker

before_install:
  - docker build -t bongardino/docker-react -f ./frontend/Dockerfile.dev ./frontend/

script:
  - docker run bongardino/docker-react npm run test -- --coverage
